//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF10.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Configuration;
    using System.Data.SqlClient;
    using System.Data;
    public partial class CabeceraFras
    {
        public int IDLINEAFRA { get; set; }
        public int IDPACIENTE { get; set; }
        public string NOMBRE_Y_APELLIDOS { get; set; }
        public string DNI { get; set; }
        [DataType(DataType.Date)]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        //[DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FECHA { get; set; }
        public string Nº_FACTURA { get; set; }
        public Nullable<decimal> TOTAL { get; set; }

        public virtual Pacientes Pacientes { get; set; }
        public string Serie;
        [DataType(DataType.Date)]
        //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MMM/yyyy}")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime fecharemesa { get; set; }
        public string Calcula_Ultima_Fra(string factura)
        {
            int pos_slash = factura.IndexOf('/');
            int pos_guion = factura.IndexOf('-');
            int dif = pos_guion - pos_slash;


            string strdigito = factura.Substring(pos_slash + 1, dif - 1);
            int numero;
            numero = Convert.ToInt16(strdigito);
            numero++;
            if (numero < 100)
            {
                strdigito = '0' + numero.ToString();
            }
            else
            {
                strdigito = numero.ToString();
            }

            string anio = factura.Substring(pos_guion + 1, 4);
            // ahora la serie
            string serie = factura.Substring(0, pos_slash + 1);

            factura = serie + strdigito + '-' + anio;
            return factura;
        }
        public static void CreaNuevaFra(CabeceraFras fra)
        {
            IVANNEntities db = new IVANNEntities();
            try
            {

                db.CabeceraFras.Add(fra);
                db.SaveChanges();

            }
            catch
            {

            }
        }
        public List<CabeceraFras> GetFrasByIDPACIENTE(int idpaciente)
        {
            CabeceraFras factura = new CabeceraFras();
            List<CabeceraFras> facturas = new List<CabeceraFras>();
            IVANNEntities db = new IVANNEntities();
            var res = db.Get_Fras_By_Id(IDPACIENTE);
            foreach (var item in res)
            {
                factura.IDLINEAFRA = item.IDLINEAFRA;
                factura.IDPACIENTE = item.IDPACIENTE;
                factura.DNI = item.DNI;
                factura.FECHA = item.FECHA;
                factura.Nº_FACTURA = item.Nº_FACTURA;
                factura.NOMBRE_Y_APELLIDOS = item.NOMBRE_Y_APELLIDOS;
                factura.TOTAL = item.TOTAL;
                facturas.Add(factura);
                factura = new CabeceraFras();
            }
            return facturas;
        }
        public string GetProximaFraTEA()
        {
            string ultimaFra = "";
            using (SqlConnection cnx = new SqlConnection(ConfigurationManager.ConnectionStrings["cnnString"].ToString()))
            {

                cnx.Open();
                //MODIFICACION INICIO AÑO 2017
                //const string sqlGetMaxFra = "SELECT * FROM ViewUltimaFraTea";
                const string sqlGetMaxFra = "SELECT * FROM View_TEA_Ultima_2017";
                using (SqlCommand cmd = new SqlCommand(sqlGetMaxFra, cnx))
                {
                    SqlDataReader dataReader = cmd.ExecuteReader();
                    while (dataReader.Read())
                    {
                        ultimaFra = dataReader.GetString(dataReader.GetOrdinal("ULTIMAFRA_TEA"));

                    }

                }

            }
            string proximaFra = Calcula_Ultima_Fra(ultimaFra);
            return proximaFra;
        }  // fin de GetUltimaFraTEA
        public string GetProximaFraCE()
        {
            string ultimaFra = "";
            using (SqlConnection cnx = new SqlConnection(ConfigurationManager.ConnectionStrings["cnnString"].ToString()))
            {

                cnx.Open();
                //modificacion inicio año 2017
                //const string sqlGetMaxFra = "SELECT * FROM View_UltimaFraCe";
                const string sqlGetMaxFra = "SELECT * FROM View_CE_Ultima_2017";
                using (SqlCommand cmd = new SqlCommand(sqlGetMaxFra, cnx))
                {
                    SqlDataReader dataReader = cmd.ExecuteReader();
                    while (dataReader.Read())
                    {
                        ultimaFra = dataReader.GetString(dataReader.GetOrdinal("ULTIMAFRA_CE"));

                    }

                }

            }
            string proximaFra = Calcula_Ultima_Fra(ultimaFra);
            return proximaFra;
        }  // fin de GetUltimaFraCE


    }
}
